adding a CSS layout for a good website
mrmrs/html pull request #31
Opened 2020-10-01 03:46 UTC by apoorvadwivedi670

ADDED A CSS LAYOUT

2020-12-19 10:57 UTC, CodeAsherPlayz commented
Closed #24

2020-12-19 10:59 UTC, CodeAsherPlayz requested changes
Just needs to fix Line 10 and 11.

2020-12-19 10:59 UTC, CodeAsherPlayz commented on index.html
> +<meta name="viewport" content="width=device-width, initial-scale=1">
Please indent this to the title. Thanks!

2020-12-19 11:05 UTC, CodeAsherPlayz commented
Link #54 here.

2023-07-31 19:30 UTC, mrmrs commented
Thanks for the pull request but I am not looking to add any styles to this page. The point is to have unstyled HTML blocks that you can have as a jumping off point. Feel free to maintain your own fork with default styles.

2023-07-31 19:30 UTC, closed without merging